#BuildStage
FROM golang:1.22.4-alpine3.19 AS builder
WORKDIR /app
COPY . .
RUN go build -o main ./cmd/api/main.go

#Run Stage
FROM alpine:3.19
WORKDIR /app
COPY --from=builder /app/main .

EXPOSE 8080
CMD ["/app/main"]